### ISSUE TITLE
Error when loading Battle.net with private profile

### ISSUE THREAD

**Issue by ajzat34** [TCNOco/TcNo-Acc-Switcher#228]
**Describe the bug**
Receiving an error if any battle.net accounts have private profiles.

**To Reproduce**
1. Add a battle.net account with a private profile, and add a battle tag
2. enable: `Show Overwatch SR and use the Overwatch profile picture`
3. wait until profile is loaded

**Expected behavior**
Handle private profiles gracefully without `An error has occurred. This application may no longer respond until reloaded.` and without failing to load other accounts.

**Screenshots**
![TcNo Error](https://user-images.githubusercontent.com/44104497/176345970-72479493-e856-42cd-ab27-6a9959666bbf.png)

**Desktop (please complete the following information):**
 - OS: `Win10 21H1`

**Additional context**
 - Downloaded `2022-05-26_01` today, replicated on another machine
 - Allow multiple instances of battle.net is enabled

```
blazor.server.js:1 
        
       [2022-06-29T03:33:17.295Z] Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at TcNo_Acc_Switcher_Server.Pages.BattleNet.BattleNetSwitcherBase.BattleNetUser.FetchRank() in C:\Users\TCNO\Documents\GitHub\TcNo-Acc-Switcher\TcNo-Acc-Switcher-Server\Pages\BattleNet\BattleNetSwitcherBase.cs:line 135
   at TcNo_Acc_Switcher_Server.Pages.BattleNet.BattleNetSwitcherFuncs.InitOverwatchMode() in C:\Users\TCNO\Documents\GitHub\TcNo-Acc-Switcher\TcNo-Acc-Switcher-Server\Pages\BattleNet\BattleNetSwitcherFuncs.cs:line 173
   at TcNo_Acc_Switcher_Server.Pages.BattleNet.BattleNetSwitcherFuncs.LoadProfiles() in C:\Users\TCNO\Documents\GitHub\TcNo-Acc-Switcher\TcNo-Acc-Switcher-Server\Pages\BattleNet\BattleNetSwitcherFuncs.cs:line 133
   at TcNo_Acc_Switcher_Server.Pages.General.GeneralFuncs.HandleFirstRender(Boolean firstRender, String platform) in C:\Users\TCNO\Documents\GitHub\TcNo-Acc-Switcher\TcNo-Acc-Switcher-Server\Pages\General\GeneralFuncs.cs:line 756
   at TcNo_Acc_Switcher_Server.Pages.BattleNet.Index.OnAfterRenderAsync(Boolean firstRender) in C:\Users\TCNO\Documents\GitHub\TcNo-Acc-Switcher\TcNo-Acc-Switcher-Server\Pages\BattleNet\Index.razor:line 113
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
```

**Comment by TcNobo** [comment]
This issue has been fixed for the next release. Hopefully should be out tomorrow or the day after.
I will post again here when it's out.

**Comment by TCNOco** [comment]
Closing this as stale and solved. Thanks for your posts even though they've gone unresponded to for so long.
The new pre-release is a full rewrite that should have this fixed, thanks for the issue.
Should you still be interested, please give it a try.
https://github.com/TCNOco/TcNo-Acc-Switcher/releases
