### ISSUE TITLE
  An error has occurred. This application may no longer respond until reloaded.

### ISSUE THREAD

**Issue by Superwheat** [TCNOco/TcNo-Acc-Switcher#405]
-09-09T10:26:38.233Z] Error: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at TcNo_Acc_Switcher_Server.Shared.ContextMenu.ContextMenu.BuildRenderTree(RenderTreeBuilder __builder) in C:\projects\tcno-acc-switcher-qih5m\TcNo-Acc-Switcher-Server\Shared\ContextMenu\ContextMenu.razor:line 33
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)

**Comment by Superwheat** [comment]
And then it fully stops working

**Comment by Superwheat** [comment]
Not working on Steam at all. No changes in settings whatsoever.

**Comment by owisia** [comment]
I have this problem too, I installed it today and it is happening from the time i installed it

**Comment by igloo15** [comment]
Looking at the Event Viewer I think this is exception in the Csharp code because you are attempting to modify a IEnumerable collection while its being used. Below is the exception I see when this error pops up

```
Unhandled exception in circuit ''.

Exception: 
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at TcNo_Acc_Switcher_Server.Shared.ContextMenu.ContextMenu.BuildRenderTree(RenderTreeBuilder __builder) in C:\projects\tcno-acc-switcher-qih5m\TcNo-Acc-Switcher-Server\Shared\ContextMenu\ContextMenu.razor:line 33
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
```

**Comment by anunknowperson** [comment]
Same problem on freshly installed account switcher

```
blazor.server.js?1746385700:1 [2025-05-04T19:08:20.961Z] Information: Normalizing '_blazor' to 'http://localhost:36352/_blazor'.
blazor.server.js?1746385700:1 [2025-05-04T19:08:20.997Z] Information: WebSocket connected to ws://localhost:36352/_blazor?id=v5woABEjYdN-nTny6PS9FA.
blazor.server.js?1746385700:1  [2025-05-04T19:08:21.781Z] Error: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at TcNo_Acc_Switcher_Server.Shared.ContextMenu.ContextMenu.BuildRenderTree(RenderTreeBuilder __builder) in C:\projects\tcno-acc-switcher-qih5m\TcNo-Acc-Switcher-Server\Shared\ContextMenu\ContextMenu.razor:line 33
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
log @ blazor.server.js?1746385700:1
unhandledError @ blazor.server.js?1746385700:1
(anonymous) @ blazor.server.js?1746385700:1
_invokeClientMethod @ blazor.server.js?1746385700:1
_processIncomingData @ blazor.server.js?1746385700:1
Xt.connection.onreceive @ blazor.server.js?1746385700:1
s.onmessage @ blazor.server.js?1746385700:1
blazor.server.js?1746385700:1 [2025-05-04T19:08:21.782Z] Information: Connection disconnected.

```

**Comment by TCNOco** [comment]
Closing this as stale and solved. Thanks for your posts even though they've gone unresponded to for so long.
The new pre-release is a full rewrite that should solve these flaky Blazor errors entirely.
Should you still be interested, please give it a try.
https://github.com/TCNOco/TcNo-Acc-Switcher/releases
